### PR TITLE
Update bootstrap.md

### PR DESCRIPTION
**Pull request by MissChocoe**
Related Ticket: 

Description of Changes:
* Added class .tox-tinymce to the closest call. This was required to make the inline editor work in bootstraop modal.

Review:
- [x] Documentation Team Lead has reviewed
- [x] Product Manager has reviewed

### CODE REVIEW

**Review by tylerkelly13 — APPROVED** [review]

**Review by lnewson — CHANGES_REQUESTED** [review]
Thanks for the contribution @MissChocoe!

Unfortunately, we'll need one other place changed before we can accept this though, as this is also in the `jQuery` integration page and they should be kept in sync. Could I ask you to please update that as well, if you're updating this?

**Comment by MissChocoe** [comment]
> Thanks for the contribution @MissChocoe!
> 
> Unfortunately, we'll need one other place changed before we can accept this though, as this is also in the `jQuery` integration page and they should be kept in sync. Could I ask you to please update that as well, if you're updating this?

Done!

**Review by JamesToohey — APPROVED** [review]

**Review by lnewson — APPROVED** [review]
> Done!

Thanks! LGTM 👍

**Review by EkimChau — APPROVED** [review]

**Comment by tylerkelly13** [comment]
Thanks for the contribution @MissChocoe !
Pushing live now, changes should be live in about 5 minutes.

**Pull request merged**
