### PR TITLE
TINY-1777: create format painter page

### PR DESCRIPTION
**Pull request by SimonFc**
Docs page for the format painter. If anything could be phrased/written in some other way to improve clarity just let me know!

### CODE REVIEW

**Comment by Afraithe** [comment]
Don't merge this in until release though.

**Comment by shikhanansi** [comment]
@SimonFc should this branch be merged now?

**Comment by SimonFc** [comment]
@shikhanansi 
Not yet - there's no set date as of now but possibly within a few weeks.
I removed the table_format_names config option in order to make the api simpler(we'll handle the details internally).

**Comment by mhideo** [comment]
@shikhanansi there is passive text and pronouns in here that need to be edited out.

**Pull request merged**
