### PR TITLE
Reduced the size of most images

### PR DESCRIPTION
**Pull request by TheSpyder**
Related Ticket: None

Description of Changes:
* This applies PNG optimisation to reduce the size of the `images/` folder by 2,534,787 bytes. I tried it based on feedback in #2021 and thought the result might be useful. 

Pre-checks:
- [ ] Branch prefixed with `feature/` or `hotfix/`
- [x] ~`_data/nav.yml` has been updated (if applicable)~
- [x] ~Files has been included where required (if applicable)~
- [x] ~Files removed have been deleted, not just excluded from the build (if applicable)~
- [x] ~(New product features only) Release Note added~

Review:
- [x] Documentation Team Lead has reviewed
- [x] Product Manager has reviewed

### CODE REVIEW

**Review by lnewson — APPROVED** [review]
We probably should consider adding a script or seeing if there is a Jekyll plugin for this, as people are likely to forget to do this as new images are added. That's a separate task though.

**Review by JamesToohey — APPROVED** [review]
🎉

**Comment by TheSpyder** [comment]
TinyPNG (which is what I used to get them even smaller than ImageOptim) has some apps available 🤔 
https://tinypng.com/third-party

**Comment by TheSpyder** [comment]
If we can find a gif optimiser (or some sort of HTML5 video) that would also be really handy. The [sticky toolbar example animation](https://github.com/tinymce/tinymce-docs/blob/main/images/sticky-toolbar.gif) is a gross 1.6 _megabytes_.

**Comment by JamesToohey** [comment]
FWIW ImageOptim on my machine shaves a fair bit more off these (and the one on the other PR), but I don't think it's worth worrying

**Comment by TheSpyder** [comment]
Your screenshot there said it shrank the original to 55% (16kb), tinypng shrank it to 26% (9kb) 🤷‍♂️

**Review by tylerkelly13 — APPROVED** [review]

**Comment by tylerkelly13** [comment]
> If we can find a gif optimiser (or some sort of HTML5 video) that would also be really handy. The [sticky toolbar example animation](https://github.com/tinymce/tinymce-docs/blob/main/images/sticky-toolbar.gif?rgh-link-date=2021-07-09T00%3A45%3A35Z) is a gross 1.6 _megabytes_.

That's _after_ I optimised it from 20+ mb

**Review by EkimChau — APPROVED** [review]

**Pull request merged**
