### PR TITLE
added smart_paste option of paste plugin

### PR DESCRIPTION
**Pull request by dev-rke**
smart_paste option of the paste plugin was not documented.

### CODE REVIEW

**Comment by techtangents** [comment]
@dev-rke In order to merge this pull request, we will need you to add your email address to your github account, make your email address publicly-visible, close this PR and create a new PR.

Apologies for the hurdle. We appreciate your contribution. We just need this information for legal purposes.

**Comment by dev-rke** [comment]
@techtangents: i will not set my email public visible. 
Why exactly do you need it?

**Comment by dev-rke** [comment]
Ok, i understand, it's about your CLA stuff....but i still don't like to publish my mail address.
Are there any alternatives?

**Comment by techtangents** [comment]
@dev-rke Unfortunately, our automated CLA process relies on email addresses being public. I appreciate you not wanting to make your address public. 

We're going to handle this documentation issue internally. We've logged an internal task to address it. 

Many thanks for helping us improve our documentation.

**Pull request closed without merging**
