### PR TITLE
Update keyboard-shortcuts.md

### PR DESCRIPTION
**Pull request by AlainRnet**
Could you add a link or an explanation to how to add custom shortcuts, please ? ;-)

### CODE REVIEW

**Comment by fyrkant** [comment]
There is [this page in the documentation](https://www.tinymce.com/docs/api/tinymce/tinymce.shortcuts/), would a link to that be enough?

**Comment by AlainRnet** [comment]
Enough? not sure : it's good but I think the documentation doesn't say where adding the code ?

**Comment by r12s** [comment]
@AlainRnet I updated this page, linking to a post we wrote for the blog explaining how to create custom shortcuts. Thanks for raising the issue! Marking closed.

**Comment by r12s** [comment]
https://www.tinymce.com/docs/advanced/keyboard-shortcuts/#addcustomshortcutstotinymce

**Pull request closed without merging**
