### PR TITLE
ASP.NET MVC upload handler

### PR DESCRIPTION
**Pull request by vanillajonathan**
A server-side upload handler ASP.NET MVC script suitable for TinyMCE.

### CODE REVIEW

**Comment by kilianc** [comment]
@vanillajonathan thanks for the contribution, please check out http://haisum.github.io/2014/11/07/jekyll-pygments-supported-highlighters/ for a list of compatible languages in pygments.

The build is breaking because `cs` is not a valid language hint, it should be `aspx-cs` or `csharp` or `c#` depending on context

**Comment by vanillajonathan** [comment]
I see. If anyone wants to fix it, they can do so.

When I saw the CLA check failed I just deleted the repository that I had forked. So I am unable to commit any fixes to the document.

https://github.com/tinymce/tinymce-docs/commit/296bd0d5dbdac21aeba53198743427121c4e9c80#diff-2e4f068d573375c68bf99d5b24befd62R12

**Comment by kilianc** [comment]
@vanillajonathan you still need to sign the CLA in order for me to merge and use these changes

**Comment by spocke** [comment]
Cla never got signed. So closing this one.

**Pull request closed without merging**
