### PR TITLE
DOC-2347 Automation script for generating new plugin docs

### PR DESCRIPTION
**Pull request by FarzadHayat**
Ticket: DOC-2347

Changes:
* Add script for generating new plugin docs
* Clean-up of templates files

Pre-checks:
- [x] Branch prefixed with `feature/7/` or `hotfix/7/`
- [x] Files has been included where required `(if applicable)`

Review:
- [ ] Documentation Team Lead has reviewed

### CODE REVIEW

**Review by kemister85 — COMMENTED** [review]
- [ ] @FarzadHayat - please do not merge this until I get a chance to review and test please.

**Review by TheSpyder — COMMENTED** [review]
I suspect those template names for folders and files will not work on a windows machine. Not all of our developers are on mac/linux.

This isn't how I would solve the problem, but if the docs team is comfortable with it I won't stand in your way.

**Comment by FarzadHayat** [comment]
@TheSpyder good point, I had not considered windows compatibility when writing this script.

While looking into this, I discovered that `tinymce-docs` default branch is not even compatible with windows because some template files in the `-new-material-templates`directory use `<` and `>` in the name which results in errors when git cloning the repo on windows. A workaround I made for this was to replace `<` and `>` with `_` and that fixed the git cloning issue. A workaround for windows is to run the script using `git bash` with only some minor tweaks to the script. 

Do you have any suggestions for how you would approach solving this problem?

**Comment by TheSpyder** [comment]
@FarzadHayat sorry, I don't always see @ pings as I get about 100 github emails a week and tend to rely on review requests.

Apparently I wasn't paying attention when I reviewed #2801!

For windows, I don't mind saying WSL is required (we do that on some of our other repositories). But that only solves the bash issue, not the filename issue.

When I said `This isn't how I would solve the problem`, what I meant was not having template files in the repo and copying them with scripts. I'd look at [yeoman](https://yeoman.io/) or another similar tool that is designed to take a template structure and fill in the gaps to generate a series of files.

**Comment by TheSpyder** [comment]
Marked as draft to stop it notifying the team until the questions are sorted out

**Comment by FarzadHayat** [comment]
This ticket has been split into multiple tickets (DOC-2469 and DOC-2470) which must be completed before this ticket.
The target branch for this PR is now archived, so I am closing this PR. Will branch out in the future using the new `tinymce/7` branch when ready for development.

**Pull request closed without merging**
