### PR TITLE
Corrects typo

### PR DESCRIPTION
**Pull request by bdjnk**
"that causes and undo" -> "that cause an undo"

### CODE REVIEW

**Comment by bdjnk** [comment]
As an aside, Ephox made this process unnecessarily aggravating.

**Comment by androb** [comment]
@bdjnk we don't mean to! What went wrong?

**Comment by bdjnk** [comment]
@androb The error message was cut off. The page it links to has too much text. I suggest: "Your email is private. Make it public so we can send you a legal document you must agree to. This is a requirement for contributing." The second error message was also cut off. It should begin: "We just sent you an email" Instead it links to the same unhelpful page, while the email is sent silently.

**Comment by r12s** [comment]
Thank you for the commit @bdjnk and for point out the problem. Appreciated! I've created an issue in our tracker and we'll take a look. Most definitely want to improve this process. Thanks.

**Pull request merged**
