### PR TITLE
TINY-3681: Add docs for base_url and suffix options

### PR DESCRIPTION
**Pull request by SimonFc**

### CODE REVIEW

**Comment by lnewson** [comment]
Will review tomorrow morning, but just wanted to ask if we can please make sure we don't merge this yet? As this is part of S11 changes and the docs are still on S10.

**Comment by SimonFc** [comment]
Of course, no hurry to merge.

**Comment by SimonFc** [comment]
@lnewson Great that you saw that!

**Comment by lnewson** [comment]
S10 has been released now, so this can be merged whenever you're happy to :) Thanks for waiting!

**Pull request merged**
