### PR TITLE
Fixed mixed up Material URLs

### PR DESCRIPTION
**Pull request by dwahlqvist**
Small detail in code, but when I was navigating the docs, it took me some time to figure that I was looking at the wrong skin :)

Related Ticket: 

Description of Changes:
* Placeholder text

Pre-checks:
- [ ] Branch prefixed with `feature/` or `hotfix/`
- [x] `_data/nav.yml` has been updated (if applicable)
- [x] Files has been included where required (if applicable)
- [x] Files removed have been deleted, not just excluded from the build (if applicable)
- [x] (New product features only) Release Note added

Review:
- [x] Documentation Team Lead has reviewed
- [ ] Product Manager has reviewed

### CODE REVIEW

**Review by tylerkelly13 — APPROVED** [review]
LGTM.

**Comment by tylerkelly13** [comment]
Hi @dwahlqvist ,

Thanks for helping out, unfortunately we cannot except this PR until you sign our Contributor License Agreement.  Typically, an email will be sent to the email address on the commit. 

FYI:
> It is fairly common for committers to use <alias>@users.noreply.github.com, as we can not identify the user making the commit, these commits will not be accepted, close the pull request, update your email, and submit a new pull request.

Please let me know if you would like to fix this up or would like me to close the PR.

Thanks
Tyler

**Review by ashfordneil — APPROVED** [review]

**Comment by dwahlqvist** [comment]
Hi @tylerkelly13 thanks for that. 
I did not receive an email regarding license. 
It's a trivial change and honestly not important for me personally, doing the PR was more like a friendly heads up to you. 
I'm fine with you closing the PR, but now you know about the error and perhaps you will fix it yourself :)

**Comment by tylerkelly13** [comment]
@dwahlqvist !

I'll close this ticket off and get this fixed up ASAP. Thanks again for pointing that issue out.

Tyler

**Pull request closed without merging**
