### PR TITLE
Initial Review of TinyMCE Docs

### PR DESCRIPTION
**Pull request by Barent**
I cleaned up the language a bit on the first steps page. I encountered some issues with ensuring my email was set up properly in order to receive the CLA. I will ensure to update the "How to Contribute" page accordingly. I also encountered a slew of issues when setting up the docs site on windows. I am thinking perhaps in the initial set up we should make a windows and OSX/Linux section. I will be attempting to perform a set up on Ubuntu this evening.

### CODE REVIEW

**Comment by Barent** [comment]
I was thinking I could use this pull request for grammatical changes, error checking, and clarity improvements. I will open issues for larger content oriented changes to ensure more discussion.

**Comment by Barent** [comment]
Rob,

Would you please review these initial doc changes and provide any feedback you might have? I just want to ensure I am on the right path. I should make more substantial edits this weekend when I have more time.

**Comment by androb** [comment]
@r12s - ping so you note Nicholas' comment.

Nick - I will try and take a look a bit later but at a WordPress conference the next few days.

**Comment by Barent** [comment]
@androb 

Andrew- No worries feel free to review at your convenience. I will still conduct some more reviews this weekend.

**Pull request merged**
